function sim_options = ui_read_options

% packet lengths vector, in bits
initial_freq = eval(get(findobj('Tag', 'Initial_Frequency'),'String'))*1000000;

magnitude = db2mag(eval(get(findobj('Tag', 'magnitude'),'String')));

enable_mask = get(findobj('Tag', 'enable_mask'),'Value');  % enable mask

% Number of ADC
num_ADC = eval(get(findobj('Tag', 'Num_ADC'),'String'));  % Num of sub ADC

num_cycles = eval(get(findobj('Tag', 'Number_of_cycles'),'String'));  % Num of cycles modeling

step = eval(get(findobj('Tag', 'step_of_frequency'),'String'))*1000000;  %  Step of frequency

% Signal to Noise Rations
% Time Skew Error
for i = 1:8
    snr_array(i) = eval(get(findobj('Tag', strcat('SNR_sub_ADC',string(i))),'String'));
end

step_of_snr = 0; % eval(get(findobj('Tag', 'step_of_SNR'),'String'));

% Error ADC modeling
error_adc = get(findobj('Tag', 'error_adc'),'Value');

% Time Skew Error
for i = 2:8
    time_skew_array(i-1) = eval(get(findobj('Tag',strcat('timeSkew',string(i))),'String'));
end
% Gain Error
for i = 2:8
    gain_error_array(i-1) = eval(get(findobj('Tag',strcat('Gain',string(i))),'String'));
end

container = 'int64';

Inter = 10;
Fs_sub_adc = 1000000000;
Fs = Fs_sub_adc * Inter * num_ADC; % Fs = 1 GHz


sim_options = struct(                           ...
   'freq',              initial_freq,           ...
   'Bit',               2048,                   ...         
   'M',                 num_ADC,                ...
   'num_cycles',        num_cycles,             ...
   'step',              step,                   ...
   'SNR',               snr_array,              ...
   'Step_of_SNR',       step_of_snr,            ...
   'MODEL_ERROR',       error_adc,              ...
   'time_skew_array',   time_skew_array,        ...
   'gain_error_array',  gain_error_array,       ...
   'Fs',                Fs,                     ... % Fs all ADC system
   'Fs_sub_adc',        Fs_sub_adc,             ...
   'Magnitude',         magnitude,              ...
   'Z',                 1,                      ...
   'N',                 73,                     ... % Number taps filters fractional delay
   'Size_matrix',       5,                      ... % Number taps adaptive out filter
   'StopTime',          0.000001,               ... % seconds
   'Inter',             Inter,                  ... % oversampling factor,                    ...
   'fractional_coeff_width',  19,               ...
   'hilbert_coeff_width',   16,                 ...                  ...
   'enable_mask',       enable_mask,            ... % включение наложения маски
   'int_size',          container,              ... % тип данных
   'type_2x2_det',      "int32",                ... % тип данных для матрицы 2х2
   'type_3x3_det',      "int64",                ... % тип данных для матрицы 3х3
   'type_4x4_det',      "int64",                ...    
   'type_5x5_det',      "int64",                ...
   'type_divide_out',   "int32",                ...
   'divide_factor',     14,                     ...
   'type_mult_in_adaptive_filter', "int64",     ...
   'type_add_in_adaptive_filter', "int64",      ...
   'width_double',		80,                     ...
   'width_fractional',  cast(32,container),     ...
   'type_fir_out',      "int16",                ...
   'width_hilbert',     cast(64,container),     ...
   'num_det2x2',        10                      ...
   );

