function sim_options = ui_read_options

% packet lengths vector, in bits
initial_freq = eval(get(findobj('Tag', 'Initial_Frequency'),'String'))*1000000;

magnitude = db2mag(eval(get(findobj('Tag', 'magnitude'),'String')));

enable_mask = get(findobj('Tag', 'enable_mask'),'Value');  % enable mask

% Number of ADC
num_ADC = eval(get(findobj('Tag', 'Num_ADC'),'String'));  % Num of sub ADC

num_cycles = eval(get(findobj('Tag', 'Number_of_cycles'),'String'));  % Num of cycles modeling

step = eval(get(findobj('Tag', 'step_of_frequency'),'String'))*1000000;  %  Step of frequency

% Signal to Noise Rations
snr = eval(get(findobj('Tag', 'SNR'),'String'));
step_of_snr = eval(get(findobj('Tag', 'step_of_SNR'),'String'));

% Error ADC modeling
error_adc = get(findobj('Tag', 'error_adc'),'Value');

% Time Skew Error
for i = 2:8
    time_skew_array(i-1) = eval(get(findobj('Tag',strcat('timeSkew',string(i))),'String'));
end
% Gain Error
for i = 2:8
    gain_error_array(i-1) = eval(get(findobj('Tag',strcat('Gain',string(i))),'String'));
end

container = 'int64';

Inter = 10;
Fs = 1000000000 * Inter * num_ADC; % Fs = 1 GHz

sim_options = struct(                           ...
   'freq',              initial_freq,           ...
   'M',                 num_ADC,                ...
   'num_cycles',        num_cycles,             ...
   'step',              step,                   ...
   'SNR',               snr,                    ...
   'Step_of_SNR',       step_of_snr,            ...
   'MODEL_ERROR',       error_adc,              ...
   'time_skew_array',   time_skew_array,        ...
   'gain_error_array',  gain_error_array,       ...
   'Fs',                Fs,                     ...    % Fs all ADC system
   'Magnitude',         magnitude,              ...
   'Z',                 1,                      ...
   'N',                 73,                     ...    % Number taps filters fractional delay
   'Size_matrix',       5,                      ...    % Number taps adaptive out filter
   'StopTime',          0.000001,               ...    % seconds
   'Inter',             Inter,                  ...    % oversampling factor,
   'Width',             14,                     ...
   'fractional_coeff_width',  19,               ...
   'hilbert_coeff_width',   16,                 ...
   'divide_remainder',  1,                      ... 
   'enable_mask',       enable_mask,            ... % включение наложения маски
   'int_size',          container,              ... % тип данных
   'type_2x2_det',      "double",               ... % тип данных для матрицы 2х2
   'type_3x3_det',      "single",               ... % тип данных для матрицы 3х3
   'width_double',		80,                     ...
   'width_fractional',  cast(32,container),     ...
   'width_hilbert',     cast(64,container),     ...
   'num_det2x2',        10,                     ...
   'remainder',         1                       ...
   );

